### ISSUE TITLE
Crashes when in a server.

### ISSUE THREAD

**Issue by Noruka** [zeroneye/Powah#1]
With the client no problem, it loads the lollipop lib and the mod but in a server it crashes it.

Crash report: https://pastebin.com/vPiLsh94

**Comment by zeroneye** [comment]
Thank you for reporting, look like some client classes trying to load on server, i  will fix the problem
Bdw, sorry for the crash :(

**Comment by zeroneye** [comment]
I fixed it in "Powah 1.14.4-0.0.5" and "Lollipop 1.14.4-0.0.9".
