### ISSUE TITLE
Ender Cell Not accepting any type of power

### ISSUE THREAD

**Issue by Sergeant102** [zeroneye/Powah#103]
#### Version: (make sure you are on the latest version before reporting):

- Minecraft: ...
- Forge: ...
- Powah: ...

#### Issue description: I have tried to use FE Power and also MJ Power not sure what I am doing wrong please advise.
...

#### Steps to reproduce: I made the ender cell and it is not working with any energy directly, do I have to use another energy cell or???
...

#### Is this a crash?, please includ it here: (Recommended to use [Gist](https://gist.github.com/))

...

**Comment by owmii** [comment]
Read the manual

**Comment by wendictive** [comment]
its in the manual page 2 (i missed that too) u have to add a cell to it
