### ISSUE TITLE
Cables don't stack when removing them from world

### ISSUE THREAD

**Issue by JonSar-GitHub** [zeroneye/Powah#104]
#### Version: (make sure you are on the latest version before reporting):

- Minecraft: 1.16.1
- Forge: 32.0.108
- Powah: 2.2.0

#### Issue description:
When removing cables from the world (re-routing, upgrading to ender gates, upgrading cable tier) then cable's don't stack (NBT I guess ? But they don't hold power worth having so pointless?) - quickly fill the inventory just with cables during base changes. 

They do stack if you manually collect each one and click onto the next one. 

#### Steps to reproduce:
Start world, place energy cable, break. 

#### Is this a crash?, please includ it here: (Recommended to use [Gist](https://gist.github.com/))

No

**Comment by Racer10** [comment]
Minecraft: 1.15.2
Forge: 31.2.31
Powah: 1.1.15

Can confirm this happens for me as well
