### ISSUE TITLE
Thermo Generator does not show bar for energy

### ISSUE THREAD

**Issue by Eydamos** [zeroneye/Powah#106]
#### Version: (make sure you are on the latest version before reporting):

- Minecraft: 1.16.1
- Forge: 32.0.108
- Powah: 2.2.0

#### Issue description:
When opening the GUI of a Thermo Generator it does not show how much energy is stored in the internal buffer on the left hand side. Only the tooltip is indicating how much power is stored. This issue affects all Thermo Generators from Starter to Nitro.

#### Steps to reproduce:
Place a Magma Block, Bucket of Lava or Block of Blazing Crystal on the ground. Place a Thermal Generator on top and feed a bucket of water to the generator.

**Comment by Eydamos** [comment]
I just was bored a little bit and thought this should be easy to fix so I scrolled through the code and found the issue.
https://github.com/owmii/Powah/blob/c5f1a8b6b96b9846fa3c0abf4e8e9e710fe8c842/src/main/java/owmii/powah/client/screen/Textures.java#L40 The width, height and u, v values are wrong. Correct would be `14, 39, 176, 0`

**Comment by owmii** [comment]
Yes, that's right thanks!!
