### ISSUE TITLE
issue

### ISSUE THREAD

**Issue by Serzh812** [zeroneye/Powah#11]
Energizing orb handles one item and you can put more (snowball + diamond, snowball - 20,30
Then it doesn't work

**Comment by owmii** [comment]
If you put more items than the recipe need then will not work, see JEI, 
You can remove item with an empty hand.

**Comment by Serzh812** [comment]
1 diamond-works
3 diamonds - not working
https://imgur.com/a/Mor46WH
you can make everything work ?

**Comment by owmii** [comment]
This is how it works, if you see the recipe in jei has multiple ingredients use the same count else will not work .
