### ISSUE TITLE
placing a reactor is a really weird experience

### ISSUE THREAD

**Issue by cpw** [zeroneye/Powah#111]
#### Version: (make sure you are on the latest version before reporting):
latest 1.16.1

#### Issue description:
if you have a player transmitter active, while crafting or picking up a reactor, parts of it start charging in your inventory. This means it's no longer placeable, until its fully charged (30M!). You get "you need X more parts", but they're present, just not in the same stack as the stack I'm trying to place now (due to not stacking because they have different levels of charge).

#### Steps to reproduce:
Place an active player transmitter. Craft the reactor in stages. You'll not be able to place it, because the parts have different charge levels. (similar applies when trying to harvest a reactor too)

**Comment by owmii** [comment]
Oh, thank you for reporting!! I will fix it in the next update.
