### ISSUE TITLE
Opening GUI w/ Powah-1.16.3-2.3.1 instantly crashes Forge server

### ISSUE THREAD

**Issue by SketchyTheGhost** [zeroneye/Powah#115]
#### Version: (make sure you are on the latest version before reporting):

- Minecraft: ... 1.16.3
- Forge: ... 34.1.23
- Powah: ... 2.3.1

#### Issue description:
... Accessing Powah! GUI while on Powah! 2.3.1 and Lollipop 3.2.1 will instantly crash server, reporting "Server Closed" in Minecraft client. 

#### Steps to reproduce:
... Accessing Furninator GUI by right-clicking block.
... Accessing Energy Cell (Basic) GUI by right-clicking block.
**... Downgrading to Powah! 2.3.0 and Lollipop 3.2.0 resolves issue.** 

#### Is this a crash?, please include it here: (Recommended to use [Gist](https://gist.github.com/))
https://gist.github.com/SketchyTheGhost/5fb087c44fa01826d36776b28ed52f21

or

[debug.log](https://github.com/owmii/Powah/files/5395687/debug.log)

...

**Comment by owmii** [comment]
The crash report, please? from the `crash-reports` folder

**Comment by SketchyTheGhost** [comment]
Here you are: 

https://gist.github.com/SketchyTheGhost/027d9a819c2e6f0d26caa6e262361029

Sorry about that! New to GitHub. :)

**Comment by owmii** [comment]
Thanks!!

**Comment by MSandro** [comment]
I have the same problem on my server

**Comment by owmii** [comment]
Fixed in Powah-1.16.3-2.3.2, Thanks for reporting!!
