### ISSUE TITLE
[1.16.3]Failed to load description for particle

### ISSUE THREAD

**Issue by Rumaruka** [zeroneye/Powah#116]
#### Version: (make sure you are on the latest version before reporting):

- Minecraft: 1.16.3
- Forge: 34.1.23
- Powah: 2.3.2
- Lollipop: 3.2.2

#### Issue description:
Failed to load description for particle
I know about this [issue](https://github.com/owmii/Powah/issues/114)
But the problem is not solved

#### Is this a crash?, please includ it here: (Recommended to use [Gist](https://gist.github.com/))
Crashlog: https://pastebin.com/zRq1gB9m
Logs: https://pastebin.com/JLptzbA5

**Comment by JasonKillsUs** [comment]
the same crash
the same version except forge xx.x.25

**Comment by JasonKillsUs** [comment]
figured out my crash, sorry was not the fault of powah

**Comment by Silvrus** [comment]
Minecraft: 1.16.3
Forge: 34.1.32
Powah: 2.3.3
Lollipop: 3.2.2

Can confirm issue is still occuring. Log attached.
https://pastebin.com/HwfB8wK4

**Comment by Xemnes-Keyethkateth** [comment]
Try disabling Immersive Engineering, I was having the same issue and that fixed it for me.

**Comment by owmii** [comment]
Disabled energizing particle temporary in v2.3.4 to fix this crash.
