### ISSUE TITLE
Powah Energy Dupe

### ISSUE THREAD

**Issue by whatthedrunk** [zeroneye/Powah#117]
Version: 
- Minecraft: 1.16.3
- Forge: 34.1.23
- Powah: 2.3.2

Issue description:
Powah Energy Dupe

Steps to reproduce:
Setup like the image. Place generator next to cell with some coal in it. Wait a few seconds and break the generator and the cells keep filling.

Screenshot and more info here. https://github.com/AllTheMods/ATM-6/issues/187

**Comment by koalalord9999** [comment]
Still an issue in powah 2.3.9
