### ISSUE TITLE
[1.16.3] Server Crash when placing a Flux Point from Flux Networks ontop of a Energy Cell.

### ISSUE THREAD

**Issue by Gbergz** [zeroneye/Powah#118]
#### Version:

- Minecraft: 1.16.3
- Forge: 34.1.25
- Powah: [1.16.3-2.3.2](https://www.curseforge.com/minecraft/mc-mods/powah/files/3084135)
- Lollipop: 1.16.3-3.2.2

#### Issue description:
Server is crashing when placing a Flux Point from Flux Networks ontop of a Energy Cell.

#### Steps to reproduce:
Place a Flux Point from Flux Networks ontop of a Energy Cell.

#### Crash-Report
https://hatebin.com/nseplgzhkg

**Comment by owmii** [comment]
I think this is a Flux Networks issue.

**Comment by Gbergz** [comment]
It was indeed, closing.
