### ISSUE TITLE
Client Crash Using Powah and Forge 34.1.27+

### ISSUE THREAD

**Issue by Darkosto** [zeroneye/Powah#119]
#### Version: (make sure you are on the latest version before reporting):

- Minecraft: 1.16.3
- Forge: 34.1.27
- Powah: 1.16.3 - 2.3.2
- Lollipop: 1.16.3 - 3.2.2

#### Issue description:
Client will crash due to an incompatibility with forge 34.1.27+

#### Steps to reproduce:

1. Load up modpack with previously stated versions of mods and forge
2. Pack will error and alert user to issue

#### Is this a crash?, please includ it here: (Recommended to use [Gist](https://gist.github.com/))

Crash report:
https://pastebin.com/66YGhL5V

**Comment by cpw** [comment]
This is blocking forgecraft updating...

**Comment by owmii** [comment]
Fixed in Powah! 2.3.3, Thanks for reporting!!
