### ISSUE TITLE
Powah failing to load correctly

### ISSUE THREAD

**Issue by picanteviento** [zeroneye/Powah#121]
[
[crash-2020-10-31_09.31.19-fml.txt](https://github.com/owmii/Powah/files/5469437/crash-2020-10-31_09.31.19-fml.txt)
](url)

**Comment by picanteviento** [comment]
Everything was loading just fine last night, but I added a couple of new mods this morning, and I wanted to know which one was causing the issue.

**Comment by owmii** [comment]
You have an old version of powah! 
Download the new one here: https://www.curseforge.com/minecraft/mc-mods/powah/files
