### ISSUE TITLE
Another Crash Issue: Glow Particle

### ISSUE THREAD

**Issue by picanteviento** [zeroneye/Powah#122]
[crash-2020-10-31_10.28.51-client.txt](https://github.com/owmii/Powah/files/5469557/crash-2020-10-31_10.28.51-client.txt)

**Comment by picanteviento** [comment]
I have the latest version of Powah installed, and it gave me this crash report.

**Comment by NielsPilgaard** [comment]
This is happening with the following versions:

`Powah-1.16.3-2.3.3`
`Forge-1.16.3.34.1.35` <-- I suspect this is the cause, 34.1.25+ has breaking changes I believe

**Comment by owmii** [comment]
Disabled energizing particle temporary in v2.3.4 to fix this crash until a finish making my own particle engine.
