### ISSUE TITLE
[1.16.3+] Impossible to disable worldgen

### ISSUE THREAD

**Issue by NielsPilgaard** [zeroneye/Powah#124]
- Minecraft: 1.16.4
- Forge: 1.16.4-35.0.9
- Powah: Powah-1.16.3-2.3.4

#### Issue description:
Disabling worldgen features in the config does nothing in-game.
Also happens in 1.16.3

Also reported this issue on Discord, but I figured traceability is nice :)

#### Steps to reproduce:
set the config `oreGen` to `false`

**Comment by owmii** [comment]
Fixed in V2.3.5, thanks for reporting!

**Comment by NielsPilgaard** [comment]
Awesome, thanks!
