### ISSUE TITLE
Server Bug, Ender device channels all the same.

### ISSUE THREAD

**Issue by KindarConrath** [zeroneye/Powah#130]
#### Version: (make sure you are on the latest version before reporting):

- Minecraft: 1.16.4
- Forge: 35.1.13
- Powah: 2.3.6

#### Issue description:
ON SERVERS, every channel other than channel 1 of the Ender Cell (And Ender Gate) are the same.
In single player it works right, but on servers  Channels 2-12 are the same.

#### Steps to reproduce:
Place down Ender Cell (higher tier, the better)
Select a channel other than 1
Shift click an Energy Cell into the channel
Check any other channel (except 1) they are all the same

Also, if you add a second Ender Cell, or an Ender gate, you can push & pull energy with any channel other than channel 1

**Comment by drtrdr23** [comment]
I can confirm this servers channels 2-12 are the same.
