### ISSUE TITLE
Dimensional power transmission not working

### ISSUE THREAD

**Issue by Zelif** [zeroneye/Powah#133]
#### Version: (make sure you are on the latest version before reporting):
[Multiplayer]
- Minecraft: 1.16.4
- Forge: 35.1.15
- Powah: 2.3.6

#### Issue description:
None of the power is being sent when a player goes to another dimension. Player transmitter + Binding Card (Dimensional) or Ender Cell are getting power outside the main dimension. 
Dimensions tried:
- Nether
- The End
- Just Another Mining Dimension

#### Steps to reproduce:
Use a player transmitter with a dimensional binding card in another dimension.

There doesn't seem to be any errors in the client or server log
I have not checked single player to see if it is working.

**Comment by owmii** [comment]
You need to keep the chunk containing the blocks loaded,

**Comment by Zelif** [comment]
> You need to keep the chunk containing the blocks loaded,

Ahh, I had someone stand near it to test thought that would have worked. Forced it to be a claimed loaded chuck and it works fine :D

**Comment by ElysiumMatt** [comment]
I have the same issue, even with all relevant chunks force loaded power does not transfer to other dimensions (tested End and Nether).
Using direwolf20 1.16 pack, no modifications. Powah-1.16.4-2.3.6.

**Comment by onlyamonth** [comment]
I have the same issue, even with all relevant chunks force loaded power does not transfer to other dimensions (tested End and Nether).
Using direwolf20 1.16 pack, no modifications. Powah-1.16.4-2.3.6.
Edit: also confirmed with latest DW pack (1.3.1) which has Powah 2.3.7.

**Comment by onlyamonth** [comment]
Information: It will not charge an elite jetpack that is being worn, but clicking the item to pick it up and then clicking again to put it back on sees it charged while in hand.
