### ISSUE TITLE
charging

### ISSUE THREAD

**Issue by Serzh812** [zeroneye/Powah#14]
after restarting the game items in the inventory are not charged
it is necessary to re create the linking map
before restarting the game
https://mega.nz/#!qlNiRCJJ!uQ32-tITUAP2Dh5qV8y1JkmAU2_RJzxYYLwuoDDtjvY
after restarting the game
https://mega.nz/#!WpdSBAhA!vJYO5FVCkRMCJRX2900yrFjoIkXNICOD8-rBsEwByEk

**Comment by owmii** [comment]
The Binding Card store the player UUID, so if different player use the card then will not work.

**Comment by Serzh812** [comment]
I play alone, offline
card name serzh ( video )
then the UUID changes, the name remains

**Comment by owmii** [comment]
Unfortunately the Binding Card require a UUID to get the right player in the existing world.
