### ISSUE TITLE
[1.16.5] JEI Energizing Rod Recipes are inaccurate

### ISSUE THREAD

**Issue by NielsPilgaard** [zeroneye/Powah#143]
#### Version: (make sure you are on the latest version before reporting):

- Minecraft: 1.16.5
- Forge: 1.16.5-36.0.10
- Powah: 1.16.4-2.3.9

#### Issue description:
The JEI recipes for the various tiers of Energizing Rods require Energizing Rods without NBT data. This is of course fine when manually crafting them, but it means that Refined Storage / Applied Energistics patterns from JEI directly do not function. 

#### Steps to reproduce:
1. Check JEI for Energizing Rod recipes past the first tier
2. Observe that the Energizing Rod is tag-less. 

Original report: https://github.com/NillerMedDild/Enigmatica6/issues/1112

**Comment by BlueAgent** [comment]
Hmm. I tried creating all the patterns from JEI only and had no issues once I put the ingredients into the system then let the crafting run for making the Energizing Rod (Nitro).
![Refined Storage crafting grid with patterns and ingredients for maing a Nitro tier Energising Rod with a single rod crafted](https://user-images.githubusercontent.com/630920/108216520-8ca61280-716d-11eb-91f0-7c496fb297fe.png)
Was using exact mode as well.

When crafting the energising rods manually it doesn't seem to have NBT data attached either.
I put the manually crafted energising rods inside a chest then use the data command to get the nbt data of the chest:
![Manually crafted energising rods not having a tag](https://user-images.githubusercontent.com/630920/108217879-0ee30680-716f-11eb-8f37-5c1c2494cb60.png)

Could not reproduce getting NBT data when crafting energizing rods.

**Comment by NielsPilgaard** [comment]
I can't reproduce it anymore either, thanks for the help 👍
