### ISSUE TITLE
Wrench in player's inventory causes server-side Exception

### ISSUE THREAD

**Issue by Tander** [zeroneye/Powah#15]
Error on server:
https://hatebin.com/imlgftueta

Happens on dedicated server: player was kicked from the server because of exception and can't join  (because exception happens again). Removing powah:whench from player's .dat file fixes it, but looks like the wrench is unusable for now.

happens on 
Powah-1.14.4-0.1.3
Lollipop-1.14.4-0.0.18

Can't test on new versions right now, i'll update this issue ASAP, but I didn't see anything about wrench in changelogs...

**Comment by owmii** [comment]
Fixed in 0.1.6, Thank you.
