### ISSUE TITLE
Crash with Optifine

### ISSUE THREAD

**Issue by Mad-Gnome** [zeroneye/Powah#16]
When placing the Cables, game crashes immediately.  Crash is repeatable, and when Optifine is removed then Cables can be placed without any issues.
Forge version-28.1.109
Powah version 1.14.4-0.19
Optifine version 1.14.4_HD_U_F4

The following error message is displayed after the crash.  

The game crashed whilst tesselating block model
Error: java.lang.ClassCastException: net.optifine.override.ChunkCacheOF cannot be cast to net.minecraft.world.IWorld

**Comment by owmii** [comment]
Fixed in v0.1.10, Thank you for reporting.
