### ISSUE TITLE
Used cables don't stack with unused cables

### ISSUE THREAD

**Issue by ghost** [zeroneye/Powah#162]
#### Version: (make sure you are on the latest version before reporting):

- Minecraft: 1.16.5
- Forge: 36.0.45
- Powah: 1.16.4-2.3.14
Modified DW20 pack.
Also see #104.

#### Issue description:
Used cables have NBT data and don't stack with unused cables.

#### Steps to reproduce:
Place cable. Break cable. Lack of success. Advanced Tooltips show 1 NBT tag. 

#### Is this a crash?, please includ it here: (Recommended to use [Gist](https://gist.github.com/))
N/A

**Comment by BlueAgent** [comment]
Can't reproduce this happening. Please test with just Powah to make sure it's not a mod interaction.


https://user-images.githubusercontent.com/630920/112858414-6b2d3480-90e4-11eb-8fa0-51b6d752c1de.mp4

**Comment by ghost** [comment]
It's not happening any more. Maybe a mod interaction, maybe an inconsistency in the web of hacks. I'll keep an eye out. I should look for a way to see NBT on an item.
