### ISSUE TITLE
Solid cables

### ISSUE THREAD

**Issue by cweckerl** [zeroneye/Powah#17]
I see the cables already have hitboxes, but do you plan on making them solid so entities cannot walk right through them? I feel this might be a good change.

**Comment by owmii** [comment]
I think Cables without the collision box are good for easy player movement.

**Comment by cweckerl** [comment]
Would a config option be possible?

**Comment by owmii** [comment]
I will try to add it in a future version.

**Comment by Pultex** [comment]
hope it is just an option having tight setups make for efficient layouts
