### ISSUE TITLE
Feature Request: Disable specific generators

### ISSUE THREAD

**Issue by UnseenAcademical** [zeroneye/Powah#170]
Hi! I love Powah and use it in most of my modpacks, but I find that the reactors and solar panels tend to mess with other mods and/or clutter JEI. I was hoping that an eventual config option could be added to disable any of the specific generators, similar to how worldgen lets you tweak things.

Thanks!

**Comment by BlueAgent** [comment]
You can hide items from JEI and disable recipes with CraftTweaker or KubeJS.
IIRC Forge now recommends mods always register all items, blocks, entities etc. Disabling functionality instead.
Configs aren't loaded till after the registries are frozen.

Also what do you mean by "mess with other mods"? Do you mean the power output is unbalanced? You can configure the generator outputs in `config/powah/energy/generators/<generator>.toml` if so. If you set it to zero generation for each of the tiers then the generators are effectively disabled.

**Comment by UnseenAcademical** [comment]
Thanks for the info! I have adjusted the power differences so they match more neatly. I mostly found that the excessive amounts of power / power for free could interfere with the pollution mechanics added by another mod, making it too easy to avoid dealing with pollution in the local area. Or making power generation from other mods obsolete too quickly.

I'm still learning my way around all the options available to modpack makers so I will follow through with the CraftTweaker/JEI option. I was not aware of the load order having already frozen the registry before config is loaded.

Thanks again!
