### ISSUE TITLE
[Suggestion] For Automation Using Refined Storage

### ISSUE THREAD

**Issue by anomalousmc** [zeroneye/Powah#175]
#### Version:

- Minecraft: 1.16.5
- Powah: 2.3.16

#### Suggestion:
I've been working hard to automate every orb energizing recipe with refined storage and most are easy enough with a bit of ingenuity. However recipes calling for 2 of the same item are nearly impossible without a complex set of timers, and the timing has to be perfect. I am referring to the Nitro Crystal energizing recipe. It's difficult to automate due to the two Redstone Blocks in the recipe. I suggest either:
1. Reducing the duplicate quantities of items and nerfing the result.
2. Or (and I like this one better) adding catalyst items and vanilla crafting recipes in place of the duplicate items, this way you would be using the same amount of items with no need to nerf the result.

So, two Redstone Blocks would craft into One Nitro Catalyst, and two Blue Ice Blocks would craft into One Dry Ice Catalyst. Then just have those single items be part of the energizing recipe.

Please and Thank You! I love your mod but these two recipes give me a headache trying to automate.

**Comment by thelapisfox** [comment]
I had the exact same issue recently. I ended up getting ALL recipes to work in RS by setting the RS crafter to 'Redstone unlocks crafting' and using the comparator value to set this. In the pack I am using, I used InDy to read the comparator value and send the redstone signal.
