### ISSUE TITLE
Server Crashes as it is un-able to find the lollipop library.

### ISSUE THREAD

**Issue by sarisman84** [zeroneye/Powah#177]
Versions:
- Minecraft: .1.16.4
- Forge: 36.1.4
- Powah: 2.3.16

#### Issue description:
Server crashes upon launching. The cause is reported to be that Powah cant find Lollipop, even though said library exists inside the mods folder in the server. 

#### Steps to reproduce:
-Create a 1.16.4 minecraft server with 36.1.4 forge jar file.
-Copy the mods folder of the client that contains Powah and Lollipop into the server's mods folder.
-Launch the server.

Here is the crash report:
[https://gist.github.com/sarisman84/4a9fbd5ae28cbba672692f8b0367322b](url)

And here is the server's mod folder with Lollipop:
![bild](https://user-images.githubusercontent.com/7117508/116668868-30961080-a99e-11eb-90b0-3900bbeed48d.png)

**Comment by BlueAgent** [comment]
Did you upload the full crash report?

There seems to be missing information.

**Comment by sarisman84** [comment]
I assumed that the crash-log file should contain the nessesary information. 

I have something to add on to this: When i inspected the general logs of the server, those logs reported an entirely different issue all together which was that the IP used was not matching the IP that was port forwarded. After some more investigation, i concluded that it was indeed a IP miss-match problem and not whatever the crash-log reported. 

My question now is; why did the crash-log file report to be unable to find Lollipop and not report the real issue of an IP miss-match?

**Comment by BlueAgent** [comment]
> ![bild](https://user-images.githubusercontent.com/7117508/116668868-30961080-a99e-11eb-90b0-3900bbeed48d.png)

I noticed that in that image it says that Lollipop was modified on 2021-29-04 at 10:11 AM but the crash report is one minute earlier:

> Time: 4/29/21 10:10 AM

> My question now is; why did the crash-log file report to be unable to find Lollipop and not report the real issue of an IP miss-match?

I don't know, obviously I can only guess.

Perhaps you accidentally started the server too quickly while downloading Lollipop Lib was still in progress so it was missing, but at the same time there was that issue there so it seems like they are related when it's not?

Does the Lollipop Lib missing crash happen consistently if you undo whatever fixed the ip? IIRC failing to port foward shouldn't cause a crash of the server... It should just run but not be accessible so I'm very confused.

Please close this issue I don't think there's any bug here.
