### ISSUE TITLE
Crash when adding binding card to player transmitter

### ISSUE THREAD

**Issue by dragon076** [zeroneye/Powah#18]
**Versions**
Powah: Powah-1.14.4-0.1.10.jar
Lollipop:Lollipop-1.14.4-0.0.21.jar
Forge: forge-1.14.4-28.1.107.jar
Modpack: Enigmatica 4 Heavily modified

This is being run as a server/client combo
The client is the only one that crashes

Whenever i put a binding card into a player transmitter via opening the gui my game exits back to the launcher.
It happens by manually dragging with the mouse or shift clicking.

![2019-12-31_12 37 44](https://user-images.githubusercontent.com/12526194/71608123-679dbb80-2bca-11ea-962b-aaa8ac37b652.png)

Here is the crash log
https://www.dropbox.com/s/hpmnxx82bcznnn0/2019-12-28-2.log?dl=0

Here is a list for the rest of the mods used
https://www.dropbox.com/s/3cp94g60ukmun7b/list.txt?dl=0

I do understand there can be many things that might cause this so let me know if u need more info

PS. I just used a hopper and the binding card was added to the player transmitter.

**Comment by owmii** [comment]
Hey dragon076! Please i need the crash report located in `.minecraft/crash-reports` folder not the log.
Thank you!

**Comment by dragon076** [comment]
Sorry i think i linked the wrong file.
This is the one i was suppose to post.
https://www.dropbox.com/s/sc7kvof7roqjflj/crash-2019-12-31_12.23.00-client.txt?dl=0

and here is a 2nd one.
https://www.dropbox.com/s/ovj318jczrw9i2z/crash-2020-01-02_00.10.43-client.txt?dl=0

**Comment by owmii** [comment]
Fixed in v0.1.11, Thank you!!

**Comment by dragon076** [comment]
Ok Thank you for your work.
Wish i could find a similar mod for handling fluids in 1.14.4.
The mods that add pipes seem almost non existent.

**Comment by dragon076** [comment]
Tested after update to v0.1.11 and seems to work as expected thanks
