### ISSUE TITLE
Cables don't connect with Enigeer's Decor small solar panel

### ISSUE THREAD

**Issue by MatthiasMann** [zeroneye/Powah#19]
Versions:
Lollipop-1.14.4-0.0.22
Powah-1.14.4-0.1.11
engineersdecor-1.14.4-1.0.18-b2

Cables next to machines or energy cells have a tile entity and a UI. Other cables not neighboring a machine or energy cell don't have a tile entity or UI (checked with F3).

The Engineer's Decor solar panels don't have an FE energy capability as they only poush power into neighboring tiles:
https://github.com/stfwi/engineers-decor/blob/master/1.14/src/main/java/wile/engineersdecor/blocks/BlockDecorSolarPanel.java#L107

That means there is no easy way to get the cables to connect with these solar panels.

I think a good work around would be to always create a tile entity when one from another mod (eg not a Powah cable) is next to a cable?

**Comment by owmii** [comment]
If the Engineer's Decor solar panels don't have an Forge energy capability then will not be compatible with any other mod cables, so this is an Engineer's Decor issue.
