### ISSUE TITLE
Solar Panel Doesn't Make Energy

### ISSUE THREAD

**Issue by PessimisticBastard** [zeroneye/Powah#2]
<a href="https://imgur.com/9p9ishY"><img src="https://i.imgur.com/9p9ishY.png" title="source: imgur.com" /></a>

<a href="https://imgur.com/8waSTZO"><img src="https://i.imgur.com/8waSTZO.png" title="source: imgur.com" /></a>

Solar panel has no blockage, and can see the sun... but it will not make energy.

**Comment by zeroneye** [comment]
I already tested them and are working properly, are you using the last version?

![2019-11-28_02 26 58](https://user-images.githubusercontent.com/12222738/69769869-01ff7f00-1187-11ea-9cdf-952663b75db8.png)

**Comment by PessimisticBastard** [comment]
The latest version I am using is 0.0.5, the latest listed on curse. I tested on new world just incase it was something with the world I was using, and it does not appear to be working either. I tested a solar panel from solar generation right next to yours, and it working.

**Comment by zeroneye** [comment]
Ok i will change how solar panels work in the next version and i will see if that solved the problem.
BDW, Thanks for reporting! :)

**Comment by zeroneye** [comment]
Changed how solar panels work, please need a feed back if are working now.

**Comment by PessimisticBastard** [comment]
Confirmed to be working.

**Comment by zeroneye** [comment]
> 
> 
> Confirmed to be working. I like the changes, btw, to the recipes. Much better, imo.
> 
> Just curious, how was it working before you changed it vs now?

I just changed the code, player will not notice any difference at all, and the generation rate are the same.
