### ISSUE TITLE
checkEnergyTile() is executed twice for non cable tiles

### ISSUE THREAD

**Issue by MatthiasMann** [zeroneye/Powah#20]
https://github.com/owmii/Powah/blob/eafb439c6192b0c66dd1c3a65a4ac479d9c8a1b9/src/main/java/owmii/powah/block/cable/CableBlock.java#L239

Should probably be stored in a local variable. Or maybe replace the boolean[] with an enum (Cable, Tile, Nothing)?

**Comment by owmii** [comment]
First check is for cable connection (cable model) and the 2nd to create the tile entity if necessary.
