### ISSUE TITLE
(suggestion):more logistics

### ISSUE THREAD

**Issue by ghost** [zeroneye/Powah#22]
so ive been playing with this mod for a while now but the thing ive noticed is that it is kind of senseless at the moment.with that i mean that there is no reason to use this mod atm there are barly any technich mods releasid and those few that are working lack logistics or features in general with wich i want to ask  weather you could not only do enerh´gy but also logistics (item/fluid)transport(or even machines).i know that this mod is faccused on energy so i would suggest maybe making it in a different mod,and yes i know that that would probably cost time so i dont have to high hopes but the fact that your current mod is so good i just had to ask

**Comment by owmii** [comment]
Hey Wotzinator!!, I'm planning to create a separate mod that include a lots of useful and unique stuffs.
Thank you for your suggestion i really appreciate it.

**Comment by ghost** [comment]
if your already planning might i suggest a few things(i havelot of ideas)?if yes shall i put them into another issue?

**Comment by owmii** [comment]
Ok!
