### ISSUE TITLE
Editing Json For Power Generation Doesn't Change in-game values

### ISSUE THREAD

**Issue by GoldenRetrieverX** [zeroneye/Powah#224]
#### Version: (make sure you are on the latest version before reporting):
- Modpack - ATM8
- Minecraft: ... 1.19.2
- Forge: ... 43.2.14
- Powah: ... 4.0.10

#### Issue description:
Edited the config/powah.json5 file to change generation rates of the different generators so they were not all the same. However JEI and the generators themselves do not reflect this change in game all still showing base values for their generation. I'm not sure if this has been covered already if it has I apologize but I cannot figure this out. I checked for any other config file but could only find the one. So I do not get why the values do not update in game. I have also created a whole new world just to see if a new world would grab the updated values and it has not.

#### Steps to reproduce:
Edit the json file and change the generation rates.

![furnator showing incorrect generation](https://github.com/owmii/Powah/assets/123786258/95a4e343-fba3-4699-ac5e-aecf9d46a3af)
![jei showing starter value not matching](https://github.com/owmii/Powah/assets/123786258/a5cc80f2-caef-46ef-8ff4-6563a0fa5e9f)
![json file edit](https://github.com/owmii/Powah/assets/123786258/10179997-8184-4505-aadc-eb72e08c6ed7)

#### Is this a crash?, please includ it here: (Recommended to use [Gist](https://gist.github.com/))

...

**Comment by GoldenRetrieverX** [comment]
Disregard. JEI was pulling from the client config not server. Edited on both and JEI and generator itself showing correct values.

**Comment by GoldenRetrieverX** [comment]
Close.

**Comment by Bluetinity** [comment]
I'm having the same issue on singleplayer. Can you elaborate on what you did exactly?
