### ISSUE TITLE
Suggestions for upcoming mod

### ISSUE THREAD

**Issue by ghost** [zeroneye/Powah#23]
here  iwant to write down a few ideas that i had for upcoming mods that owmii plans.note that these are only concepts so i dont know if they will fit in.

world generation
-ores like tin and copper(i know its very cliche but it could be interesting if these ores would be fleahed out)
-a few new useful plants.with this i mean that most plants and vanilla are primarily used for food instead of technology.i would want plants that are used in industry like canola wicgh could be used for stuff like fuel and energy generation.
-natural gas and oil.eventhough a few mods add oil(and near to none have natural gas)i think that those are quite interesting in the energy generation sector.youd need to get them out of reservoiurs wich you would need to find.and those reservours will empty over time wich means you will have to move your machinery from time to time.you would need to distill the oil before using it.
-plastic wich yould be sythesiced out of oil,gas and plant matter.it is meant as a machine building component and would fit the estatcic.
not only different tiers of machines but also classes with wich i mean size classes to be exact 2 classes(normal,industrial) the normal ones would be well normal sized blocks used in a casual setting with a medium speed efficiency cost and power consumption.then theindustrial size wich would mean multiblocks(like the reactor)those are bigger multiblocks whose cost and consumption would be higher but would also be more efficient. in advance i would recommend that some machines only exist in certain classes for example the nuclear reactor in the industrial class
     -(industrial)ball mill:a big ball mill wich would grind ors into chunks wich can be refiend further into more dust
     -(normal)mill:a small mill that is pretty much the normal tech mod grinder
     -(Industrial)Steam turbine:a big steam turbine wich uses high temperatur steam to generate masses of electricity
      -(industrial)gas turbine: a big turbine that burnes gas and fuels won from oil to generate power
      -(Industrial)Boiler:a big boiler generating normal heat steam from coal and oil
      -(industrial)steam engine block:a big steam engine block wich uses normal heat steam to generate energy(meant to get more power out of coal)
      -(normal+industrial)electrolizer:it takes in water and power to get oxygen and hydrogen
      -(industrial+normal)tanks:tanks that come in 2 sizes small(one block) and big(i dunno how big yet)both are meant for storing liquids and gasses
-pipes and pumps:these pipesare meant for fluid and gass transport.pumps can be used(when powered)to increase the flow rate and controll the flow direction.they would be broader than the electricity cables and show the content.
-pneumatic item pipes:these would be for item transport.you could see the items traveling in the pipes.they rely on air pressure so you need compressors(they determine the speed).filters would also be useful

**Comment by owmii** [comment]
Thank you so much for taking your time to write this ideas i really appreciate it.  ❤💎

**Comment by ghost** [comment]
i hope they arent to impossible or to much of your ideas
