### ISSUE TITLE
This version crashing server

### ISSUE THREAD

**Issue by CarlucciMods** [zeroneye/Powah#26]
forge 28.1.115 Server on 1.14.4 

[crash-2020-01-20_20.35.58-server.txt](https://github.com/owmii/Powah/files/4088839/crash-2020-01-20_20.35.58-server.txt)
[crash-2020-01-20_20.33.28-server.txt](https://github.com/owmii/Powah/files/4088840/crash-2020-01-20_20.33.28-server.txt)

old version works fine, this new update server will not load. Client load up seems fine.

**Comment by owmii** [comment]
Thank you for reporting!!
Just forgot to set required lollipop version to v0.0.23.
Fixed in v0.2.4.
