### ISSUE TITLE
Server Crashing due to new config file, 

### ISSUE THREAD

**Issue by CarlucciMods** [zeroneye/Powah#27]
forge 28.1.115 on 1.14.4 MC

Server crashes on new release. Rolled back to previous release server still will not load. Found out the new config file that was loaded with new release was casuing the issues, deleted config file, ran previous version server runs fine now but cant use new release . 

[crash-2020-01-20_21.02.24-server.txt](https://github.com/owmii/Powah/files/4092028/crash-2020-01-20_21.02.24-server.txt)
[crash-2020-01-20_21.04.24-server.txt](https://github.com/owmii/Powah/files/4092029/crash-2020-01-20_21.04.24-server.txt)
[crash-2020-01-20_21.05.43-server.txt](https://github.com/owmii/Powah/files/4092030/crash-2020-01-20_21.05.43-server.txt)
[crash-2020-01-20_22.24.10-server.txt](https://github.com/owmii/Powah/files/4092031/crash-2020-01-20_22.24.10-server.txt)
[crash-2020-01-20_22.27.52-server.txt](https://github.com/owmii/Powah/files/4092032/crash-2020-01-20_22.27.52-server.txt)
[crash-2020-01-20_22.31.41-server.txt](https://github.com/owmii/Powah/files/4092033/crash-2020-01-20_22.31.41-server.txt)
[crash-2020-01-20_20.58.51-server.txt](https://github.com/owmii/Powah/files/4092034/crash-2020-01-20_20.58.51-server.txt)

**Comment by owmii** [comment]
Your using outdated versions: `Lollipop-1.14.4-0.0.22` and `Powah-1.14.4-0.2.2`.
Update to the new version: https://www.curseforge.com/minecraft/mc-mods/powah/files
and here https://www.curseforge.com/minecraft/mc-mods/lollipop/files

**Comment by CarlucciMods** [comment]
Ive tried new version thats what got the crash started in the first place !

**Comment by owmii** [comment]
But all crash reports are from the old versions `Lollipop-1.14.4-0.0.22` and `Powah-1.14.4-0.2.2`
