### ISSUE TITLE
Textures not loading in newest version

### ISSUE THREAD

**Issue by CarlucciMods** [zeroneye/Powah#28]
no resource packs loaded. 

Forge 28.1.115 on 1.14.4

![2020-01-22_19 38 34](https://user-images.githubusercontent.com/31194015/72947073-ea8bdf00-3d4e-11ea-957c-31288de58fdf.png)
![2020-01-22_19 38 37](https://user-images.githubusercontent.com/31194015/72947074-ea8bdf00-3d4e-11ea-94a8-29c65e38b59a.png)

**Comment by owmii** [comment]
Thanks for reporting!! Fixed in v0.2.5.

**Comment by CarlucciMods** [comment]
any time, kick ass mod !
