### ISSUE TITLE
GREAT WORK ON THE NEW UPDATE ! WOahh

### ISSUE THREAD

**Issue by CarlucciMods** [zeroneye/Powah#29]
I need some help, I watched all the videos I can on your mod but no one has been able to help me, nor your in game book. 

Things I need info on >

1. Energy Storage (Energy Cell, Ender Network) < What the heck is this (ender stuff only)  and how do i use it if i dont have anything ENDER, 1.14.4 doesnt have anything ported yet regarding ender stuff.

2. Ender Network (Ender Cell, Ender, Gate) < What the heck is this and how do i use it if i dont have anything ENDER, 1.14.4 doesnt have anything ported yet regarding ender stuff.

3 Energy Hopper < no worries i foudn in book

4. Water logging support. < what is this ? Please be very detailed !

Tip: maybe expand you in game book to cover Everything.....which better detail, still good job. 

Also when i run shaders and or texture packs, the items dont look like your photo ! see image

Also would be good if the enegry orb can play nice with refined storage, you know export gold and iron into orb, the import energized item out into system. aha
![2020-01-24_18 22 02](https://user-images.githubusercontent.com/31194015/73110961-6ebc9e80-3ed6-11ea-8802-bb25ed049262.png)

**Comment by owmii** [comment]
**Ender cells/gates** are just a normal type of energy storage that works like **ender chest** but for energy, (read the book for how to use it).

**Water logging** mean you can place water in same block position.

For shader: that's his problem not mine!

Please for any question use: https://discord.gg/A8TP9JY for fast answer!
