### ISSUE TITLE
Upgrades ? no one has any detailed info on this, maybe we can get a book made ?

### ISSUE THREAD

**Issue by CarlucciMods** [zeroneye/Powah#31]
Can you tell us what upgrades work best with what machines, generators, etc....i dont want to be using an upgrade in a machine that won't use it.......

Example, energy efficiency upgrade, what machines can use this properly ? 

also energy capacity upgrade doesn't seem to want to be made, no recipe ? also what machine can use this one ?

**Comment by owmii** [comment]
Are you sure you are not in the wrong repository, because i don't have any upgrades in my mods 🤣.
