### ISSUE TITLE
Formerly "Requesting Energizing orb hold only one item per round of energizing. #30"

### ISSUE THREAD

**Issue by CarlucciMods** [zeroneye/Powah#33]
Please see video in link...

https://vimeo.com/user79498309/review/388641070/1bc9b54193

**Comment by CarlucciMods** [comment]
also if i autocraft more then one item, and a diamond needs to be changed over to a Nicotic Crystal, the orb still takes more then one diamond and comes to a hault.

**Comment by owmii** [comment]
Sorry search on youtube on how to use auto crafter

**Comment by owmii** [comment]
and please dont open duplicate issue.
