### ISSUE TITLE
Texture conflict with Soartex Fanver x64 texture pack or any pack I use !

### ISSUE THREAD

**Issue by CarlucciMods** [zeroneye/Powah#34]
I am sorry if I am becoming a bother or a pain in the ass. I was just hoping input is also a good thing no matter who it comes from, anyway I have to say Great Mod, from one modder to another.....Hard work pays off, you are a very special person to give your time to make others enjoy there game more. Now.......

![2020-02-01_22 12 55](https://user-images.githubusercontent.com/31194015/73602327-04dc6e80-4540-11ea-8061-de11fe270df4.png)
![2020-02-01_22 12 58](https://user-images.githubusercontent.com/31194015/73602328-04dc6e80-4540-11ea-83fd-99a12caa388e.png)

see images for conflicts, was woundering what Texture packs out there does you mod support ? Also anyway to get mod support for Soartex Fanver x64.......

**Comment by owmii** [comment]
That's a shader problem not from Soartex Texture pack, and i can't fix it because I'm not the dev of that shader.
