### ISSUE TITLE
Negative buffer on Furnator

### ISSUE THREAD

**Issue by asimenio-asteri** [zeroneye/Powah#35]
It is as the title says. Here's a screenshot:
![image](https://user-images.githubusercontent.com/51142390/73618822-da49ee80-45ef-11ea-931e-038e29c331df.png)
I don't know if it's because the item that caused this can smelt 4,608 items, but I think it is. As of typing this, the buffer has gone down to -67%.
Edit: The buffer starts at -55%

**Comment by owmii** [comment]
What fuel you are using?

**Comment by asimenio-asteri** [comment]
I am using Aeternalis Fuel Block, from ProjectE

**Comment by asimenio-asteri** [comment]
(sorry for late reply)

**Comment by asimenio-asteri** [comment]
And also, at around -72%, it flips back to positive numbers, so then 72% 71% ect

**Comment by owmii** [comment]
The problem here is that Aeternalis Fuel Block has a very high fuel value that when get multiplied the number pass the integer max value returning a negative value.

**Comment by asimenio-asteri** [comment]
Ok, that's what I thought was happening. But the fuel still works, it just display wrong
