### ISSUE TITLE
Energizing Orb Item Vanishing

### ISSUE THREAD

**Issue by DJToxica** [zeroneye/Powah#38]
Hello owmii,

first i love your mod to bits! Great work.
Yesterday i was working on how to automate the energizing orb with refined storage,
Seems like there is no viable way at the moment but maybe you can give me a hint?

But to get to the point, i tested what would happen if i just put in a bunch of blaze rods. The Orb accepted the whole stack (didn't really think about it) but when i right clicked it, it gave back only 5.

I think there is a bug where the orb accepts more than it can hold and just voids excess items?

I haven't yet upgraded to something higher than the base one. I could test it in a creative world.
This is our modpack if it is a compatibility bug:
https://www.curseforge.com/minecraft/modpacks/game-server-germany-survival-server-modpack

Regards
DJ

**Comment by owmii** [comment]
The energizing orb designed to process 1 item per slot/stack, i will see how i can force it to not accept more than that.
For the energizing orb automation i'v seen **[Wyld](https://t.co/cjNWGvIKYW?amp=1)** using Xnet to do that by limiting stack size to one, also there is a screenshot of energizing orb automation in the general channel in my discord: https://discordapp.com/invite/A8TP9JY.
