### ISSUE TITLE
 [1.15.2-1.0.2] Ticking Block Entity

### ISSUE THREAD

**Issue by kreezxil** [zeroneye/Powah#39]
1.15.2-1.0.2 crashes dedicated server Forge 1.15.2 build 31.1.14

Notes:
     Ticking Block Entity

crash report:
http://paste.ubuntu.com/p/vf7k2NwFRK/

fml server latest:
http://paste.ubuntu.com/p/qb6Dxpmwhj/

**Comment by kreezxil** [comment]
this might be in your lib, also I see you have 1.0.3 out of powah. I'll install that next to see if things go better.

**Comment by owmii** [comment]
When is the crash happen? trying to open a gui?

**Comment by kreezxil** [comment]
when I placed the generated next to a flux cable. and the only way to fix
it was to delete the mod. so sad. will try again on your next update.

I have discovered a problem with using nbtexplorer on region files.
apparently deleting tags from chunks no longer works. the world on a server
seems to repair the entries.

**Comment by kreezxil** [comment]
this issue with region files only showed up with 1.15.2 worlds, 1.14.4
worlds are still editable.

**Comment by owmii** [comment]
The crash caused by another mod called `flux`:
```
-- Block entity being ticked --
Details:
	Name: flux:energy_cable // szewek.flux.tile.EnergyCableTile
	Block: Block{flux:energy_cable}[down=true,east=false,north=false,south=true,up=true,west=false]
	Block location: World: (-269,61,-165), Chunk: (at 3,3,11 in -17,-11; contains blocks -272,0,-176 to -257,255,-161), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
	Block: Block{flux:energy_cable}[down=true,east=false,north=false,south=true,up=true,west=false]
	Block location: World: (-269,61,-165), Chunk: (at 3,3,11 in -17,-11; contains blocks -272,0,-176 to -257,255,-161), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
```
The tile entity with id `flux:energy_cable` caused the crash.
