### ISSUE TITLE
Capacitors Blaze and Above Are Perhaps a Bit Expensive

### ISSUE THREAD

**Issue by PessimisticBastard** [zeroneye/Powah#4]
Having to go hunt down a Nether Fortress, standing and clicking on 8 blazes, then hunting down unmined 4 diamond ores, and then hunting down two emerald ores, the rarest in the game, that only spawns in relatively rare biomes seems a bit much for a single machine. 

I realize they are meant to be the end game, but that seems a bit much. Especially for a battery that holds slightly more power than a few large RF tools power cell (hardly the most OP mod in existence) or a few end-tier Thermal Expansion/Enderio capacitors.

My suggestion, if you are to keep this mechanic, then perhaps increase the amount of capacitors you can get per ore to 8?

Or, perhaps, instead of using ore blocks, you use the capacitors on a diamond/emerald block (with 9 per block?)

**Comment by zeroneye** [comment]
I will try to increase the amount of energy stored by a capacitor depending on how expensive it is, for now until i add some new less expensive tiers.
Thank you for your feed back!

**Comment by PessimisticBastard** [comment]
The other problem with this approach is that it's not really able to be automated. The blazes.. it can be done, if you have a way to get a blaze spawner + auto clicker, but ores are, without Mekanism in existence for 1.14.4, not really doable.

**Comment by zeroneye** [comment]
I will do my best to fairly tweak/change the mod in the next versions.
Thank you i appreciate your help. 😉

**Comment by zeroneye** [comment]
Added blazing ,Niotic and Spirited Capacitor crafting recipes.
Tweaked Energy Cells capacities.
