### ISSUE TITLE
Manual 2 items pages has the same text

### ISSUE THREAD

**Issue by Sunekaer** [zeroneye/Powah#40]
Charged Snowball and Lens of Ender 
In the manual for these two items it has the same text.
Not sure use if they does the same thing or this is an error :)
![image](https://user-images.githubusercontent.com/18720460/74863126-a3910980-534d-11ea-8bf3-97a0b772c005.png)
![image](https://user-images.githubusercontent.com/18720460/74863132-a855bd80-534d-11ea-95f0-a6f52d345cfd.png)

**Comment by Sunekaer** [comment]
Version: Powah-1.15.2-1.1.0

**Comment by owmii** [comment]
Fixed in v1.1.2, Thanks for reporting.
