### ISSUE TITLE
Cant place on 1.15.2 ATM5 server

### ISSUE THREAD

**Issue by karlreinert** [zeroneye/Powah#43]
I cannot place the Reactor multiblock when playing on a Server world run by akliz. 

When I do try to do it my blocks dissapare from inventory and I can see someting hapen infront of me, but the strukture is see through and blocks me from coming through. Can only break maybe one of I can find it. 

No problems placing in a singleplayer world using the same mods. 

I run All the mods 5 modpack version 1.5 with a few extra mods DimStorage, Powah, Lollipop, StorageDrawers, ChunkNoGoByeBye, DankStorage, and MixInBootstrap. All newest versions.

**Comment by owmii** [comment]
What version of powah you're runing?

**Comment by owmii** [comment]
Just fixed in 1.0.4, thanks for reporting!
