### ISSUE TITLE
Reactor Block doesn't form on server.

### ISSUE THREAD

**Issue by Yamza** [zeroneye/Powah#44]
Placing the reactor blocks doesn't initiate the reactor formation, and the blocks becomes glitched meaning it cannot be removed. Placing any blocks in the space where the reactor block was causes them to turn into the reactor block. This only happens on server, not on SSP.
https://i.imgur.com/0ZM7mod.png 
https://i.imgur.com/t0OcCSg.png

This error shows up in console as well when the block is broken. 
https://hatebin.com/klhkkiwtwa

Powah-1.15.2-1.1.3.jar
Lollipop-1.15.2-1.0.5.jar
forge-31.1.14

**Comment by Yamza** [comment]
I see this was fixed already.. I'll just see myself out.

**Comment by owmii** [comment]
BTW, thanks for reporting!
