### ISSUE TITLE
Solar panel crashing on servers.

### ISSUE THREAD

**Issue by Darkere** [zeroneye/Powah#45]
forge-31.1.14
Powah-1.15.2-1.1.3
Lollipop-1.15.2-1.0.5

Crash report: https://hatebin.com/vtgwllpmmm

**Comment by owmii** [comment]
Already fixed that in v1.1.4
Thanks for reporting.

**Comment by Darkere** [comment]
ah ok. sorry

**Comment by owmii** [comment]
No problem
