### ISSUE TITLE
bindig card crash

### ISSUE THREAD

**Issue by MUHAKLorTheDorfTrottel4Github** [zeroneye/Powah#46]
mc 1.15.2
forge-1.15.2-31.1.14
Powah-1.15.2-1.1.4
Mekanism-**1.15.2-9.9.10.402** ( generator, tools )

If you place a Binding card ( dimensional ) bound to a player ( me)
in the  powered Player transmitter (nitro) , 
and then try to place any mekanism item (miner, cubes ) , that uses Rf/FE , same owner, the game crash.
after restart ( world ) the item is there and working.

removing the card, you can place anything you want 

no problem with omega craft ultimate EDS, 
no problem with your energy cells
no problem with rftools powercells ( are not charging in inventory)

it may a mekanism problem, I just wanted to notice

regards

**Comment by owmii** [comment]
Ok i will try to see what's the problem, thanks for reporting.

**Comment by owmii** [comment]
Crash report?

**Comment by QPUNeptune** [comment]
ima leave the crash report here
[crash-2020-02-24_03.14.31-client.txt](https://github.com/owmii/Powah/files/4243015/crash-2020-02-24_03.14.31-client.txt)

**Comment by owmii** [comment]
@QPUNeptune please open a new issue.

**Comment by QPUNeptune** [comment]
even tho is the same issue?

**Comment by QPUNeptune** [comment]
btw same versions

**Comment by owmii** [comment]
No, it's different, and i'm just trying to fix it right now.

**Comment by QPUNeptune** [comment]
ight thx and sorry for the problem
