### ISSUE TITLE
[Powah 1.15.2-1.1.4] [Lollipop 1.15.2-1.0.6] Binding card (Dimensional) crash

### ISSUE THREAD

**Issue by QPUNeptune** [zeroneye/Powah#47]
Minecraft 1.15.2
Forge 1.15.2 31.1.14
Powah 1.15.2-1.1.4
Lollipop 1.15.2-1.0.6
Mekanism(Generators/Tools) 1.15.2-9.9.10.402

Placing a Binding card (Dimensional) bound to a player on a Player Transmitter (Hardened)
causes a java.lang.NullPointerException: Ticking block entity error.
The server runs just fine, but I can't enter it without crashing my MC client.
Here's the crash report:
[crash-2020-02-24_03.47.17-client.txt](https://github.com/owmii/Powah/files/4243046/crash-2020-02-24_03.47.17-client.txt)

**Comment by owmii** [comment]
Thanks!! next release will be uploaded in a moment with the fix.

**Comment by owmii** [comment]
Fixed in v1.1.5, Thanks for repotring.

**Comment by QPUNeptune** [comment]
Thanks for your amazing work.
