### ISSUE TITLE
[Bug] Recipes do not generate properly in multiplayer. Tested on "Open to LAN".

### ISSUE THREAD

**Issue by LeafSoap** [zeroneye/Powah#48]
Everything works normally as the host. For other players, this is the result when looking at the "uses" for energizing:

https://imgur.com/a/OcQ9X5D

Crafttweaker recipes also do not generate for other players. They are not bugged like the similar image, but they simply do not appear. Host can see all recipes as normal.

**Comment by owmii** [comment]
Your using some mod that removed diamond tag/or-dictionary from the game, if you see it say's `Empty tag: forge:gems/diamond` and that's clearly not a bug.

For Crafttweaker i have to test it in lane world and see.

**Comment by owmii** [comment]
Just fixed that in v1.1.9, thanks for reporting.
Also added support for energizing recipes from json like vanilla, examples: http://bit.ly/3baHdLr.
