### ISSUE TITLE
[1.15.1/?] Feature registration happening during synchronous event leading to potential race condition

### ISSUE THREAD

**Issue by noobanidus** [zeroneye/Powah#49]
As far as I can tell, `IFeatures.register` is only called from the `FMLCommonSetupEvent`, which, as far as I'm aware, is still part of the asynchronous event chain.

This can lead to the possibility of features being registered for all biomes, *before* all biomes have actually been registered, meaning some biomes do not have ores, etc, generated in them.

Moving this call to a `FMLLoadCompleteEvent` would, I believe, solve this situation.

**Comment by owmii** [comment]
i think i found the problem, i'm using `Biome.BIOMES ` instead i sould use `ForgeRegistries.BIOMES`

**Comment by noobanidus** [comment]
You know, I was literally explaining the issue to someone in a DM and they asked me to file the issue as I understood it more ***and I completely forgot to mention that you were using the wrong Biome registry***, whoops! My bad, sorry.

**Comment by owmii** [comment]
No problem, BTW, Thank you ♥
