### ISSUE TITLE
Cables

### ISSUE THREAD

**Issue by ChilledDayZ07** [zeroneye/Powah#5]
Power cables don’t stack or connect transfer FE.

**Comment by PessimisticBastard** [comment]
Hmm, can't confirm that one. I just tried the cables with both gravity generators from quirkygenerators and transferred from a battery to a Useless furnace. Can you take pictures from your setup? Also, my cables are indeed stacking.

**Comment by PessimisticBastard** [comment]
Okay, bit of an update, this is odd. I added a bunch of cabling to move power from my power plant and into my storage house, and now it's not sending power. It's receiving power from the generator just fine, but won't send it.

**Comment by PessimisticBastard** [comment]
Related issue, it seems like the cables sometimes drain energy from machines that are not generators/batteries. I connected my refined storage system to the cable network, and all the power just  drained right out of it.

**Comment by ChilledDayZ07** [comment]
I’ll try to post a setup pic tomorrow for you. Great mod by the way I really like it.

**Comment by zeroneye** [comment]
> 
> 
> Power cables don’t stack or connect transfer FE.

I Already Fixed cables stack size from 1 to 64 in the beta 0.0.8 yesterday.

> 
> 
> Related issue, it seems like the cables sometimes drain energy from machines that are not generators/batteries. I connected my refined storage system to the cable network, and all the power just drained right out of it.

The problem here is from refined storage , there machines accept to extract energy, i will report that to him today :)

**Comment by zeroneye** [comment]
Just reported the issue to raoulvdberge : https://github.com/raoulvdberge/refinedstorage/issues/2361
