### ISSUE TITLE
1.15.2 update

### ISSUE THREAD

**Issue by OlRusty** [zeroneye/Powah#50]
I really love this mod, it's super good but i have found the following issues

-energy cells and cables when setting side config does not change when connect and being supplied with power
-ender cell and ender gate doesnt seem to change channels
-playing on a multiplayer server using this mod and sometimes items disappear from the energy cells? (not entirely sure)
-cables not displaying how much rf they have stored

i hope you do polish up this mod because it's super good, keep up the good work and i know it's new to 1.15.2. The dimensional binding card caught me off guard by the way.

once again i love this mod and i hope you keep up the good work on it. thank you for an excellent mod.

**Comment by owmii** [comment]
Just fixed that in v1.1.9, thanks for reporting.
