### ISSUE TITLE
Compressed Packet Possible Issue

### ISSUE THREAD

**Issue by ghost** [zeroneye/Powah#51]
Preface: I don't know this issue is with Powah itself, we just have narrowed it down to a possibility. I'm filing the report hoping that someone sees it and it strikes them that they know why it could possibly happen. Feel free to close this, it's more of a notification than an issue, since we are not sure. 

Background: We have twice now (2 different servers, same pack which is in testing for release) made bases that once rendered immediately kick out any player within range for the connection lost image attached. The common setup between those was an energizing orb which was having items (emeralds, i think) into it by xnet. Pics attached. 

Does that make any sense? Could a xnet setting lead to a packet problem? Thanks for the help :)

Thanks!

![2020-03-01_09 24 50](https://user-images.githubusercontent.com/38612528/75814645-1a6fce80-5d60-11ea-937a-f25abf77f08c.png)
![unknown](https://user-images.githubusercontent.com/38612528/75814647-1ba0fb80-5d60-11ea-8f03-f55aea6f47f5.png)

**Comment by owmii** [comment]
Can i have the server crash report?

**Comment by owmii** [comment]
Server crash report?.

**Comment by ghost** [comment]
Sorry, server never crashed because of it. It was just kicking out anyone who got too close. It showed that packet error and then sent players back to the main menu. Relogs weren't possible afterwards, until someone moved their player data away from the setup.

**Comment by owmii** [comment]
I looked everywhere in the inter-web found similar problems here: https://github.com/FTBTeam/FTB-Continuum/issues/451
and here: https://github.com/SpongePowered/SpongeForge/issues/2569
Look like this happen when overloading a server chunk by transferring a lots of items with large nbt data between chests.

**Comment by ghost** [comment]
Ahhhh, I understand better now. Thank you for the research and explanation. Looks like we did it to ourselves, haha
