### ISSUE TITLE
JEI Energizing 

### ISSUE THREAD

**Issue by Sunekaer** [zeroneye/Powah#52]
Hi

When checking Energizing recipes is sometimes says that tags are empty, mostly happens on a server, only seen it once or twice in SP, and the items do have the tags and the recipe does work
![image](https://user-images.githubusercontent.com/18720460/76170435-2d303c00-6182-11ea-8162-a198d70e4119.png)

![image](https://user-images.githubusercontent.com/18720460/76170525-e7c03e80-6182-11ea-8011-ac46daa8a922.png)

**Comment by owmii** [comment]
This is a known forge bug: (server tags not sync to the client). Try `/reload` and see.
