### ISSUE TITLE
Magmatic Generator can void excess lava

### ISSUE THREAD

**Issue by NielsPilgaard** [zeroneye/Powah#54]
When filling the Magmatic Generator with a Fluid Tank from the Large Fluid Tank mod, any excess amount of lava remaining in the fluid tank will be voided.

If I have a Fluid tank with 100000mB of lava, and click a Magmatic Generator (Niotic), it'll fill the generator, and I will lose 100000 - 18000mB of lava.

This issue could be on Large Fluid Tank's side, but I thought I'd start here :)

### Versions
- Powah-1.14.4-0.2.7
- LargeFluidTank-14.9.6

### Logs
https://gist.github.com/NillerMedDild/fa577468af9bfde713464f1c7396c94b

**Comment by owmii** [comment]
I need to test it myself with the Large Fluid Tank mod and see whats the problem, thanks for reporting!!

**Comment by BlueAgent** [comment]
I can't seem to reproduce this bug using the following versions of both mods:

- Powah-1.16.4-2.3.12
- LargeFluidTank-16.1.5

Must have been fixed at some point.

<details>
<summary>Screenshots</summary>

**Before (1048536 Buckets)**
![Tank filled with 1048536 buckets of lava](https://user-images.githubusercontent.com/630920/108588560-d3c21c80-7394-11eb-89b4-1921476ac667.png)
**After (1048532 Buckets, Difference -4 Buckets)**
![Tank filled with 1048532 buckets of lava](https://user-images.githubusercontent.com/630920/108588562-d6247680-7394-11eb-96a1-f2ccb5a83af0.png)
</details>

**Comment by NielsPilgaard** [comment]
Me neither, thanks! :)
