### ISSUE TITLE
Strange Issue Setting Redstone mode

### ISSUE THREAD

**Issue by DinnerBeef** [zeroneye/Powah#55]
This video explains it.

https://drive.google.com/file/d/1LVGfeVronnTEYlIuNwsHHcBKuKtj3p37/view?usp=drivesdk

**Comment by DinnerBeef** [comment]
btw this only happens on server an not in SP

**Comment by owmii** [comment]
Thanks for reporting!!, I will see what the problem.

**Comment by owmii** [comment]
Fixed in v1.1.9
Thanks for reporting.
