### ISSUE TITLE
Please stop making scripts each time the game loads

### ISSUE THREAD

**Issue by jaredlll08** [zeroneye/Powah#56]
I'm talking about this:
https://github.com/owmii/Powah/blob/1.15/src/main/java/owmii/powah/compat/crafttweaker/CrafttweakerCompat.java#L38-L57

We do have the docs:
https://docs.blamejared.com

I would be more than happy to host your docs there instead of having that file generate (and always generate even if someone deletes it)

**Comment by owmii** [comment]
Hey, I will add a command line to generate the example file instead of making scripts each time the game load, thanks for reporting!!

**Comment by NielsPilgaard** [comment]
I would also appreciate if you PR'd docs to https://docs.blamejared.com, it's really nice to have all the docs centralized :)
