### ISSUE TITLE
You're making your Energizing recipes way too early.

### ISSUE THREAD

**Issue by jaredlll08** [zeroneye/Powah#57]
Recipes and Tags are only filled when you connect to a server / join a world, so by having your recipe invocation here you can't use the tags, you just end up with things like:
![image](https://user-images.githubusercontent.com/5553605/76670657-614c9800-659a-11ea-917e-e78103dd9c99.png)

With the iron and gold tags being empty.
https://github.com/owmii/Powah/blob/1.15/src/main/java/owmii/powah/Powah.java#L45

**Comment by owmii** [comment]
Thanks!! i will fix it in the next release.
