### ISSUE TITLE
Powered Snowball

### ISSUE THREAD

**Issue by DinnerBeef** [zeroneye/Powah#58]
https://pastebin.com/ih4ZLJwL
This happens when I launch with opfine. Yes I know opfine does wired things but still want to report it in case you forgot to do something with it and or did something wrong the might affect people in different ways

**Comment by DinnerBeef** [comment]
also in case, you want to fix it so people can use opfine with your mod

**Comment by chrmatique** [comment]
I'm also having this issue, Minecraft 1.15.2 with Optifine preview 
https://pastebin.com/KrhjZyiy

**Comment by owmii** [comment]
Optifine 1.15.2 is not compatible with Forge yet. You'll have to wait until it is. You can see it for example on the changelog
