### ISSUE TITLE
Unable to change channels on Endercell (Powah-1.15.2-1.1.11)

### ISSUE THREAD

**Issue by joshuathomas2** [zeroneye/Powah#61]
When I click to change a channel on the Endercell nothing happens. I saw that this got fixed in the previous version, but it seems to still be happening.

Forge version: 31.1.25

**Comment by owmii** [comment]
Latest server log please?

**Comment by joshuathomas2** [comment]
https://pastebin.com/Uw6KWtbL

**Comment by owmii** [comment]
That's weird, the server log has no error, do you still get the problem?

**Comment by joshuathomas2** [comment]
Upon further investigation in a creative world, I discovered that the Starter tier only has access to 1 channel. I did not realize this. I don't think I saw this mentioned in the Powah! manual. My bad! Sorry about that.

**Comment by owmii** [comment]
Oh, no problem
