### ISSUE TITLE
[1.15.2] Feature request - recipe for block ores

### ISSUE THREAD

**Issue by kwpugh** [zeroneye/Powah#62]
Hi,

Could you add smelting recipes for the block forms of your ores please?   Using a Silk Touch quarry leads to lots of ores to break.

Thank you for considering.

Regards.

**Comment by owmii** [comment]
Hi kwpugh, uraninite ore are effected by fortune enchant so its not smeltable :[
but you can add it using datapack :]

**Comment by kwpugh** [comment]
Can't you do both?   Diamond Ore is affected by fortune and its smeltable if you silk touch the ore.

**Comment by owmii** [comment]
Oh, ok i will add it next release!

**Comment by kwpugh** [comment]
Thank you.
