### ISSUE TITLE
[1.15.2] You should add Uraninite to forge ingots.

### ISSUE THREAD

**Issue by mjlmjl888** [zeroneye/Powah#63]
For example all copper ingots are forge:ingots/copper.
So they should be forge:ingots/uraninite.
You could also use gems or dusts instead of ingots.

**Comment by pokemonlover1234** [comment]
Could also do this for the uraninite ores

**Comment by pokemonlover1234** [comment]
From the modpack issue i linked the developer of that modpack has stated that the block form of the ores do actually have a forge:ores tag, but that the item forms of the ore blocks do not. As a correction to my above comment in light of this:

Could also add a tag to the item form of the ore blocks
