### ISSUE TITLE
Gear and machines

### ISSUE THREAD

**Issue by LCTMarti** [zeroneye/Powah#7]
Features which would be cool: 
- Something that makes the machines faster (like capacitors in EnderIO)
- Add gear which can be filled with FE for faster mining speed, more armor points and more damage
- Make it so the "Power Bank" can charge stuff or make a seperate block which is a charger (would also make sense to add a wireless one then)

**Comment by zeroneye** [comment]
I like all of your ideas , i will add them all soon , the energy cell and all generators including solar panels all have 2 charging slots, Thank you!
