### ISSUE TITLE
Inconsistent Energy Cell (Hardened) Recipe

### ISSUE THREAD

**Issue by NielsPilgaard** [zeroneye/Powah#71]
#### Version: (make sure you are on the latest version before reporting):

- Minecraft: 1.15.2
- Forge: 1.15.2-31.1.44
- Powah: Powah-1.15.2-1.1.12

#### Issue description:
The Energy Cell (Hardened) recipe required 4 of the previous tier Energy Cells, although all the other Energy Cell recipes only require 2 of the previous tier.

I suggest you change the recipe to this, in order to make the recipes consistent:
![billede](https://user-images.githubusercontent.com/21295394/79270136-d9f68b00-7e9d-11ea-92e1-785a33b266f9.png)

**Comment by owmii** [comment]
I will add it next release, Thanks!!
