### ISSUE TITLE
Energizing orb deleting extra input

### ISSUE THREAD

**Issue by merlerm** [zeroneye/Powah#75]
I put 32 iron and 32 gold all at once in an orb in an attempt to craft quickly. When I saw that didn't work, i broke the orb to get them back and it only dropped 4 iron, which correspond to the ones that were rendered. Is this a known issue?

**Comment by owmii** [comment]
How did you put 32 iron and gold to the orb that only accepts 6 items?

**Comment by merlerm** [comment]
i just kept right clicking and they kept going in. forgot to mention i'm running Powah 1.1.12 on Enigmatica 5 0.4.8

**Comment by namstor** [comment]
This happened to me also.  Running Valhelsia 2 v 2.17

Put a stack of diamonds in and got 6 back (right clicked the entire stack in)
