### ISSUE TITLE
dropping

### ISSUE THREAD

**Issue by Serzh812** [zeroneye/Powah#8]
It is possible to solve the problem with dropping
[https://github.com/desht/ModularRouters/issues/63#issuecomment-561253931](url)
[https://github.com/desht/ModularRouters/issues/63#issuecomment-561419746](url)
[https://github.com/zeroneye/Powah/tree/master/src/main/resources/data/powah/loot_tables/blocks](url)

**Comment by zeroneye** [comment]
Thank you for reporting!!, i will fix it in the next version.
BDW, sorry, my mistake -_-.

**Comment by zeroneye** [comment]
Fixed in Beta v0.0.15!
Sorry again.

**Comment by Serzh812** [comment]
all is well
