### ISSUE TITLE
Multiple Energizing Orbs next to each other seam to bug teh Energizing Rods

### ISSUE THREAD

**Issue by FKammerer45** [zeroneye/Powah#82]
#### Version: (make sure you are on the latest version before reporting):

- Minecraft: ...1.15.2
- Forge: ...31.1.87
- Powah: ...Powah-1.15.2-1.1.14.jar

#### Issue description:
...Multiple Energizing Orbs next to each other seem to bug the Energizing Rods

#### Steps to reproduce:
...
Multiple Energizing Orbs next to each other seem to bug the Energizing Rods
#### Is this a crash?, please includ it here: (Recommended to use [Gist](https://gist.github.com/))

...No Crash

**Comment by owmii** [comment]
"bug the Energizing Rods" !!??, any further clarification please.
