### ISSUE TITLE
Reactor Output changing as a function of fuel level

### ISSUE THREAD

**Issue by brad18** [zeroneye/Powah#83]
#### Version: (make sure you are on the latest version before reporting):

- Minecraft: 1.15.2
- Forge: 31.1.77
- Powah: 1.1.14

#### Issue description:
Not sure if intentional but the reactor rf output is related to the amount of fuel available. So at 1000/1000mb I get 88krf/t on the nitro reactor but as it falls to 900/1000mb (before it inputs the next piece of uraninite), it gradually falls to 80krf/t then bounces back up to 88krf/t.

#### Steps to reproduce:
N/A

#### Is this a crash?, please includ it here: (Recommended to use [Gist](https://gist.github.com/))
N/A

**Comment by owmii** [comment]
That's not a bug :), read the book for more info.
