### ISSUE TITLE
[1.15.2 SSP] Energy Cell Config

### ISSUE THREAD

**Issue by OCDCleric** [zeroneye/Powah#85]
#### Version:

- Minecraft: 1.15.2
- Forge: 31.1.74
- Powah: 1.1.14

#### Issue description:
Energy Cell forgets i/o configuration.

#### Steps to reproduce:
1. Set i/o config for energy cell.
2. Close SSP World.
3. Open SSP World and check cells i/o config to see it has forgotten.

#### Is this a crash?, please includ it here: (Recommended to use [Gist](https://gist.github.com/))

...

**Comment by owmii** [comment]
This happen only when the config is incorrect, please check the min/max before setting a value.
Eg: if the max cap is 1000 and you set it to 2000 the cap will get reset to the 1000.

**Comment by OCDCleric** [comment]
I have a feeling i didnt specify properly. I meant the ingame enegy cells io config.

**Comment by owmii** [comment]
I didn't add any in-game config, you can edit the config manually from the config folder.
It would also require a game restart to apply it correctly.
