### ISSUE TITLE
[1.16] Client Crash with player transmitter

### ISSUE THREAD

**Issue by WhitePhant0m** [zeroneye/Powah#90]
#### Version: (make sure you are on the latest version before reporting):

- Minecraft: 1.16.1
- Forge: 32.0.63
- Powah: Powah-1.16.1-2.0.2

#### Issue description:
Game crashed after placing down a player transmitter and putting the dimensional card in there.
Note that this happens on ATM6 BYG server, haven't been able to replicate on their other server nor in SP

#### Steps to reproduce:
Place down a player transmitter and put a dimensional card in, after that, crash.

#### Is this a crash?, please includ it here: (Recommended to use [Gist](https://gist.github.com/))
[Crash Log](https://gist.github.com/AleksiMK/25c524b324e42839b4ceb1de92de03ea)

**Comment by owmii** [comment]
Fixed in v2.0.3.
Thanks for reporting !!
