### ISSUE TITLE
Crashing on client and server load

### ISSUE THREAD

**Issue by whatthedrunk** [zeroneye/Powah#93]
Crashing on client and server load

- Minecraft: ...1.16.1
- Forge: ... 32.0.67
- Powah: ... 1-2.0.4

https://pastebin.com/Z5TKRHfD

**Comment by owmii** [comment]
Forge added a new way to register commands in 32.0.67 that I didn't know about it.
Thanks for reporting!!

**Comment by owmii** [comment]
Fixed in v2.1.0
