### ISSUE TITLE
Not all uraninite ores are in the forge:ores/uraninite tag

### ISSUE THREAD

**Issue by LordMZTE** [zeroneye/Powah#96]
#### Version: (make sure you are on the latest version before reporting):

- Minecraft: 1.15.2
- Forge: 31.2.30
- Powah: 1.1.14

#### Issue description:
only the normal uraninite ore is in the forge:ores/uraninite tag, dense and poor ones arent
#### Steps to reproduce:
look at [this file](https://github.com/owmii/Powah/blob/1.15/src/main/resources/data/forge/tags/blocks/ores/uraninite.json) :P

#### Is this a crash?, please includ it here: (Recommended to use [Gist](https://gist.github.com/))
no crash

**Comment by owmii** [comment]
Added in V2.1.2, Thanks for reporting!!
